services:
  qr-generator-api:
    build:
      context: .
      dockerfile: Dockerfile
    
    ports:
      - "8080:8080"
    
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

    restart: always

    depends_on:
      mysql_db:
        condition: service_healthy
    
    networks:
      - qr_network

  mysql_db:
    image: mysql:8.0.33
    
    ports:
      - "3306:3306"
    
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: qr_db
    
    volumes:
      - mysql_data:/var/lib/mysql
    
    restart: always

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    
    networks:
      - qr_network

volumes:
  mysql_data:

networks:
  qr_network:
    driver: bridge
